[Settings]
; マウス感度
MouseSensitivity=0.400000
; パッドの横軸感度
PadSensitivityX=0.500000
; パッドの縦軸感度
PadSensitivityY=0.400000
; エイム中の感度減衰率
AimSencePercent=0.5			

[Player]
HP=100						; 体力
MaxWalkSpeed=600			; 移動速度
Acceleration=2048			; 歩き出し加速度
Gravity=2.2					; 重力
Friction=8					; 地面との抵抗
JumpForce=800				; ジャンプ力
AirControl=0.5				; 空中での入力受け付け率
AirFriction=0.05			; 空中での抵抗

[Enemy]
HP=50				; 体力
MoveSpeed=300			; 移動速度
AttackRate=2			; 攻撃頻度
AttackPower=20			; 攻撃力
RangedAttackSpeed=800		; 攻撃速度

[Gun]
FireRate=0.5			; 射撃速度
Damage=10			;
Magazine=30			;

[Reverse]
ReverseTime=300			;
ReverseCoolDownTime=300		;
ReverseSpeed=2.0		;

